import type { HyperstarToolName } from "./tool-metadata.js";

const scopes = {
  create_campaign_creator_import: ["campaigns:write"],
  confirm_campaign_creator_import: ["campaigns:write"],
  get_campaign_creator_import: ["campaigns:read"],
  get_campaign_creator_import_results: ["campaigns:read"],
  cancel_campaign_creator_import: ["campaigns:write"],
  get_workspace_usage: ["usage:read"],
  check_operation_capacity: ["usage:read"],

  start_browser_login: [],
  complete_browser_login: [],
  hyperstar_whoami: [],
  list_workspaces: [],
  select_workspace: [],
  get_hyperstar_workflow_guide: [],
  search_creators: ["search:read"],
  get_search_results: ["search:read"],
  get_creator: ["search:read"],
  list_campaigns: ["campaigns:read"],
  get_campaign: ["campaigns:read"],
  list_campaign_creators: ["campaigns:read"],
  get_campaign_workflow_counts: ["campaigns:read"],
  create_campaign: ["campaigns:write"],
  update_campaign: ["campaigns:write"],
  save_search_results_to_campaign: ["campaigns:write"],
  add_campaign_creator: ["campaigns:write"],
  update_campaign_creator: ["campaigns:write"],
  prepare_campaign_creator_selection: ["campaigns:write"],
  copy_campaign_creators: ["campaigns:write"],
  remove_campaign_creators: ["campaigns:write"],
  start_email_unlock: ["campaigns:write"],
  get_email_unlock_job: ["campaigns:write"],
  check_bulk_email_readiness: ["campaigns:read"],
  start_bulk_email: ["bulk_email:write"],
  get_bulk_email_job: ["bulk_email:write"],
  list_campaign_email_waves: ["campaigns:read"],
  get_campaign_email_wave: ["campaigns:read"],
  list_email_senders: ["bulk_email:write"],
  cancel_campaign_email_wave: ["bulk_email:write"],
  retry_campaign_email_wave: ["bulk_email:write"],
  list_inbox_threads: ["inbox:read"],
  get_inbox_thread_messages: ["inbox:read"],
  get_inbox_aggregates: ["inbox:read"],
  update_inbox_thread_state: ["inbox:write"],
  send_inbox_reply: ["inbox:write"],
  get_message_attachment_download: ["inbox:read"],
  get_campaign_performance: ["performance:read"],
  list_campaign_creator_performance: ["performance:read"],
  list_campaign_video_performance: ["performance:read"],
  get_campaign_video_history: ["performance:read"],
  get_campaign_revenue: ["performance:read"],
  list_forms: ["forms:read"],
  get_form: ["forms:read"],
  create_form: ["forms:write"],
  update_form: ["forms:write"],
  delete_form: ["forms:write"],
  // Transfer permissions depend on the persisted target; the API enforces them.
  create_file_upload: [],
  get_file_upload: [],
  complete_file_upload: [],
  cancel_file_upload: [],
  list_campaign_creator_files: ["campaigns:read"],
  get_campaign_file_download: ["campaigns:read"],
  remove_campaign_file: ["campaigns:write"],
} as const satisfies Record<HyperstarToolName, readonly string[]>;

export function toolScopes(name: HyperstarToolName): string[] {
  return [...scopes[name]];
}
